VidyaVortex/DataVortex/urls.py
# urls.py for VidyaVortex project 2015-2016

from django.conf.urls import url
from DataVortex import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.home, name="homepage"),
    url(r'^faq/$', views.faq, name="faqpage"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', login, {'template_name': 'DataVortex/login.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page': 'homepage'}, name="logout"),
    url(r'^playgame/(\d+)/$', views.playgame, name="playgame"),
    url(r'^ajax/$', views.ajax, name="ajax"),
    url(r'^addgame/$', views.addgame, name='addgame'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^purchase/(\d+)/$', views.purchase, name="purchase"),
    url(r'^purchase_failed/$', views.purchase_failed, name="purchase_failed"),
    url(r'^purchase_successful/$', views.purchase_successful, name="purchase_successful"),
    url(r'^delete/(\d+)/$', views.delete, name="delete"),
    url(r'^highscores/$', views.highscores, name='highscores'),
    url(r'^editgame/(\d+)/$', views.editgame, name="editgame"),
    url(r'^salesinfo/(\d+)/$', views.salesinfo, name="salesinfo"),
    url(r'^verify/$', views.verify, name='verify'),
    url(r'^api/$', views.api, name='api')
]

VidyaVortex/VidyaVortex/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from DataVortex import urls as data_urls

urlpatterns = [
    url(r'^', include(data_urls)),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VidyaVortex/DataVortex/models.py
# models.py for VidyaVortex project 2015-2016

from django.db import models
from django.contrib.auth.models import User, Group
from django.core.validators import MinValueValidator, URLValidator
from django.core.exceptions import ValidationError
from decimal import Decimal


# general (global) game object model
class Game(models.Model):

    # checks if image file size is not over 5MB and it has valid file extension
    def image_check(fieldfile_obj):
        extension = fieldfile_obj.file.name.split('.')[1]
        filesize = fieldfile_obj.file.size
        megabyte_limit = 5.0
        if filesize > megabyte_limit*1024*1024:
            raise ValidationError("Max image size is %sMB" % str(megabyte_limit))
        if extension != "png" and extension != "jpg" and extension != "gif":
            raise ValidationError("Supported file formats are: png, jpg, gif")

    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    buycount = models.PositiveIntegerField(default=0)
    url = models.URLField(max_length=200, unique=True, default="https://example.com/game.html",
                          validators=[URLValidator(schemes=["https"], message="Please provide a valid https URL")])
    description = models.TextField(blank=True)
    # thumbnail = models.FileField(upload_to='thumbnails', null=True, validators=[image_check]) 
    # had to discard file uploading feature as Heroku is unwilling to host anything in MEDIA_ROOT for some reason
    thumbnail = models.URLField(max_length=200, blank=True, null=True, default="https://example.com/myimage.png")
    price = models.DecimalField(max_digits=7, decimal_places=2, default=0,
                                validators=[MinValueValidator(Decimal('0.00'))])
    rating = models.IntegerField(default=0)
    time = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ['name']


# user spesific game object model
class MyGame(models.Model):
    game = models.ForeignKey(Game, blank=True, null=True)
    player = models.ForeignKey(User, blank=True, null=True)
    gamestate = models.TextField(blank=True)
    rated = models.BooleanField(default=False)

    class Meta:
        ordering = ['game']


# highscore object model with relations to both above objects
class Highscore(models.Model):
    value = models.FloatField()
    game = models.ForeignKey(Game, blank=True, null=True)
    mygame = models.ForeignKey(MyGame, blank=True, null=True)
    
    class Meta:
        ordering = ['-value']


# used to track information on purchases of games
class Purchase(models.Model):
    amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    buyer = models.ForeignKey(User, blank=True, null=True)
    game = models.ForeignKey(Game, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField(default=False)


# used to check if user has completed email verification
# apikey is also included in verification email which enables the use of this web service's non public api 
class Verification(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    apikey = models.CharField(max_length=32, unique=True)

VidyaVortex/DataVortex/forms.py
# forms.py for VidyaVortex project 2015-2016

from django import forms
from DataVortex.models import Game


# Used for user registration, quite self-explanatory
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, label="Username", required=True)
    email = forms.EmailField(label="Email address", required=True)
    password = forms.CharField(widget=forms.PasswordInput, label="Password", required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, label="Repeat password", required=True)
    developer = forms.ChoiceField(required=True, widget=forms.RadioSelect,
                                  choices=(("dev", "Developer"), ("player", "Player"),), label="Select account type:")


# Simple verification form used to check if user really wants to delete his game
class BoolForm(forms.Form):
    accept = forms.BooleanField(label="accept", widget=forms.HiddenInput)


# used in addgame view, links certain Game model fields to this form
class UploadForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = ('name', 'url', 'description', 'price', 'thumbnail')


# bound form with hidden inputs, used to communicate with payment service
class PurchaseForm(forms.Form):
    pid = forms.IntegerField(required=True, label="pid", widget=forms.HiddenInput)
    sid = forms.CharField(label="sid", widget=forms.HiddenInput)
    amount = forms.DecimalField(max_digits=9, decimal_places=2, label="amount", widget=forms.HiddenInput)
    success_url = forms.URLField(label="success_url", widget=forms.HiddenInput)
    cancel_url = forms.URLField(label="cancel_url", widget=forms.HiddenInput)
    error_url = forms.URLField(label="error_url", widget=forms.HiddenInput)
    checksum = forms.CharField(label="checksum", widget=forms.HiddenInput)


# extended UploadForm for editgame view. 
# The use of this form allows giving your game the same name and url as before when editing a game
class EditForm(forms.ModelForm):

    name = forms.CharField(max_length=100, label="name", required=False)
    url = forms.URLField(max_length=200, label="url", required=False)
    
    class Meta:
        model = Game
        fields = ('description', 'price', 'thumbnail')

VidyaVortex/DataVortex/views.py
# views.py for VidyaVortex project 2015-2016

import json
import uuid
from hashlib import md5
from decimal import Decimal

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.core import mail
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Min
from django.http import HttpResponse, Http404, HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.utils.datastructures import MultiValueDictKeyError

from DataVortex.forms import RegisterForm, UploadForm, PurchaseForm, BoolForm, EditForm
from DataVortex.models import Game, MyGame, Highscore, Purchase, Verification
from VidyaVortex.settings import SELLER_ID, SELLER_KEY, LOCATION_URL


# function to check whether request.user is developer
# return value of this function is often passed as a context variable to templates in order to render it correctly
def isdev(request):
    try:
        return request.user.groups.filter(name='developers').exists()
    except ObjectDoesNotExist:
        return False


# function to check whether request.user is owner of the game spesified by game_id
def isowner(request, game_id):
    try:
        game = Game.objects.get(id=game_id)
        return MyGame.objects.filter(player=request.user).filter(game=game).exists()
    except ObjectDoesNotExist:
        return False


# function to check whether request.user is both developer and the owner of the game
# in other words, whether he has the right to delete this game
def can_delete(request, game_id):
    return isowner(request, game_id) == isdev(request) == True


# display homepage template
def home(request):
    if request.method == 'GET':
        return render(request, 'DataVortex/homepage.html', {'isDev': isdev(request)})


# display browse.html template
def browse(request):
    if request.method == 'GET':
        return render(request, 'DataVortex/browse.html', {'isDev': isdev(request)})


# display highscores.html template
def highscores(request):
    if request.method == 'GET':
        return render(request, 'DataVortex/highscores.html', {'isDev': isdev(request)})


# display faqpage template
def faq(request):
    if request.method == 'GET':
        return render(request, 'DataVortex/faq.html', {'isDev': isdev(request)})


# register a new user with data submitted with form
def register(request):
    # Handle sent form data
    if request.method == 'POST':

        # store post data to 'form' object
        form = RegisterForm(request.POST)

        # check if form data is valid
        if form.is_valid():
            data = form.cleaned_data

            # check if password was typed correctly
            if data['password'] == data['password2']:

                # check if the input username already exists in database
                if User.objects.filter(username=data['username']).count() == 0:

                    # check if the input email address already exists in database
                    if User.objects.filter(email=data['email']).count() == 0:

                        # All ok! --> create new user
                        user = User.objects.create_user(data['username'], data['email'], data['password'])

                        # set the new user to the right user group
                        if data['developer'] == 'dev':
                            group, created = Group.objects.get_or_create(name='developers')
                        # add the registered user to developers' group

                        else:
                            group, created = Group.objects.get_or_create(name='players')
                        # add the registered user to players' group

                        user.groups.add(group.pk)
                        user.save()

                        # generate email verification token
                        ver_str = data["email"] + "VidyaVortex" + data["username"]
                        ver_token = md5(ver_str.encode("utf-8")).hexdigest()

                        apikey = uuid.uuid4().hex
                        ver = Verification.objects.create(user=user, apikey=apikey)
                        ver.save()

                        # send email verification link to user's email address (or in this demo case, to Django console)
                        with mail.get_connection() as connection:
                            subject = "VidyaVortex account verification"
                            body = "Click this link to verify your account:\nhttp://" + LOCATION_URL +\
                                   "/verify?token=" + ver_token + "&username=" + data["username"] +\
                                   "\nYour apikey is. " + apikey

                            mail.EmailMessage(subject, body, "verify@vidyavortex", [data["email"]],
                                              connection=connection).send()

                        state = 1  # registration successful
                    else:
                        state = 5  # email address already taken
                else:
                    state = 4  # username already taken
            else:
                state = 3  # password confirmation failed
        else:
            state = 2  # form data invalid

    # initialize new empty form
    elif request.method == 'GET':
        form = RegisterForm()  # new empty form
        state = 0  # do not display registration information

    # render the register page according to dict variables and send HttpResponse
    return render(request, 'DataVortex/register.html', {'form': form, 'state': state, 'isDev': isdev(request)})


# view to verify user's email
# email has been sent to user containing link with valid token to this view
def verify(request):
    data = request.GET
    if "token" not in data or "username" not in data:
        return HttpResponseBadRequest()
    if not User.objects.filter(username=data["username"]).exists():
        raise Http404("No such user")

    token = data["token"]
    u = User.objects.get(username=data["username"])

    ver_str = u.email + "VidyaVortex" + u.get_username()
    ver_token = md5(ver_str.encode("utf-8")).hexdigest()
    if token != ver_token:
        raise Http404("Invalid token")
    u.verification.verified = True
    u.verification.save()
    return HttpResponse("<h1>Verification succesful!</h1>")


# game service view, returns playgame.html with context variables
@login_required(login_url="login")
def playgame(request, game_id):
    if request.method == 'GET':

        try:
            game = Game.objects.get(id=game_id)

        except Game.DoesNotExist:
            raise Http404()

        context = {'game_url': game.url,
                   'game_name': game.name,
                   'game_id': game_id,
                   'isDev': isdev(request)}
        try:
            my_games = MyGame.objects.filter(player=request.user)
            my_games.get(game=game)
        except ObjectDoesNotExist:
            # user needs to purchase this game first
            if not isdev(request):  # devs can't purchase games
                return redirect("purchase", game_id)
            else: 
                return redirect("homepage")

        # most of game service functionality is implemented in the template (JavaScript)
        # and ajax view with JSON communication
        return render(request, 'DataVortex/playgame.html', context)

    return redirect("homepage")


# view to handle ajax requests, a lot of this website's functionality is based on this view
def ajax(request):

    # make sure XmlHttpRequest header is included in the request
    if request.is_ajax():

        # only accept post method
        if request.method == 'POST':

            # extract the payload from the HTTP request in JSON format
            jsondata = json.loads(request.body.decode('utf-8'))
            game_id = jsondata['game_id']
            jsondata = jsondata['data']

            # check message type
            try: 
                mtype = jsondata['messageType']
            except KeyError:
                return HttpResponse(json.dumps({'messageType': 'ERROR', 'info': 'Unidentified request!'}),
                                    content_type="application/json")

            # the request associated to spesific game
            if game_id > 0:

                # user must be logged in
                if request.user.is_authenticated():

                    # access current user's game collection and find active game
                    try:
                        my_games = MyGame.objects.filter(player=request.user)
                        current_game = Game.objects.get(id=game_id)
                        my_game = my_games.get(game=current_game)
                    except ObjectDoesNotExist:
                        return HttpResponse(json.dumps({'messageType': 'ERROR', 'info': 'Game data not found!'}),
                                            content_type="application/json")

                    # request to save score to the server was sent
                    if mtype == 'SCORE':
                        try:
                            score = jsondata['score']
                        except KeyError:
                            return HttpResponse(json.dumps({'messageType': 'ERROR',
                                                            'info': 'Failed to save highscore!'}),
                                                content_type="application/json")

                        scores = []

                        # only save relevant scores, i.e. ones that are higher than zero
                        if score > 0:
                            # create new highscore object
                            highscores = my_game.highscore_set
                            lowest_score_value = highscores.aggregate(Min('value'))
                            newhighscore = Highscore(value=score, game=current_game, mygame=my_game)

VidyaVortex/DataVortex/templates/DataVortex/addgame.html
<!DOCTYPE html>
<html>
  <head>
    <title>VidyaVortex - Dive into the World of Video Games</title>
    
    <meta name="description" content="Add a new game page for VidyaVortex Web Service, Project WSD 2015">
    <meta charset="utf-8" />

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static "DataVortex/img/favicon.png" %}">
    <script src="{% static "DataVortex/js/jquery-1.11.1.min.js" %}"></script> 

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="{% static "DataVortex/css/main.css" %}" />
  </head>
  <body>	
  	<div id="bg">
  		<div id="container">
		  	<div id="header">
				<div id="logo">
					<a href="{% url "homepage" %}"><img src="{% static "DataVortex/img/logo.png" %}" alt="VidyaVortexLogo"/></a>
				</div>
				<div id="loginbar">
					{% if not user.is_authenticated %}
						<p><a href="{% url "login" %}">Login</a> <b>|</b> <a href="{% url "register" %}">Register</a></p>
					{% else %}
						<p><a href="{% url "logout" %}">Logout</a> <b>|</b> Welcome, {{ user.get_username }}!</p>
					{% endif %}
				</div>
			</div>
			<div id="content">
				<div id="sidebar">
					<ul>
						<li><a href="{% url "homepage" %}">HOME</a></li>
						{% if isDev %}
						<li><a href="{% url "addgame" %}">ADD NEW GAME</a></li>
						{% endif %}
						<li><a href="{% url "browse" %}">BROWSE GAMES</a></li>
						<li><a href="{% url "highscores" %}">HIGHSCORES</a></li>
						<li><a href="{% url "faqpage" %}">FAQ</a></li>
					</ul>
				</div>
				<div id="content-box">
					{% if edit %}
					<h2>Edit game: {{ game_name }}</h2>
					<form action="/editgame/{{game_id}}/" method="post" class="form-inline" enctype="multipart/form-data">
					{% else %}
					<h2>Put a new game on sale:</h2>
					<form action="{% url "addgame" %}" method="post" class="form-inline" enctype="multipart/form-data">
					{% endif %}
					  {% csrf_token %} 
					    <p><label for="id_name">Give a name for your game:</label>
					    	{% if error == 2 %}
					    	<ul><li>There already exists another game with this name.</li></ul>
					    	{% endif %}
   							{{ form.name.errors }}
   							{{ form.name }}
   							{% if edit %}<span>(optional)</span>{% endif %}
  						</p>
  						<p><label for="id_url">Enter the URL to your game:</label>
  							{% if error == 1 %}
  							<ul><li>Please provide a valid https URL.</li></ul>
  							{% elif error == 3 %}
  							<ul><li>There already exists another game with this url.</li></ul>
  							{% endif %}
   							{{ form.url.errors }}
   							{{ form.url }}
   							{% if edit %}<span>(optional)</span>{% endif %}
  						</p>
  						<p><label for="id_price">Choose a price for purchasing your game:</label>
   							{{ form.price.errors }}
   							{{ form.price }}
   							<span>€</span>
  						</p>
  						<p><label id="description_label" for="id_description">Describe your game:</label>
   							{{ form.description.errors }}
   							{{ form.description }}
  						</p>
  						<p><label id="thumbnail_label" for="id_thumbnail">Give an URL to a screenshot of your game:</label>
   							{{ form.thumbnail.errors }}
   							{{ form.thumbnail }}
  						</p>
					  	<input type="submit" value="Submit" />
					</form>
					<div id="error">
					{% if state == 1 %}
						<h2>Congratulations! Game added successfully!</h2>
					{% elif state == 2 %}
						<h2>Congratulations! Game edited successfully!</h2>
					{% endif %}
					</div>
				</div>
			</div>
			<div id="footer">
				<div id="footer-text">
					<p>Copyright © VidyaVortex. All rights reserved. Design by WSD-Group.</p>
				</div>
			</div>
		</div>
	 </div>
  </body>
</html>

VidyaVortex/DataVortex/templates/DataVortex/browse.html
<!DOCTYPE html>
<html>
  <head>
    <title>VidyaVortex - Dive into the World of Video Games</title>
    
    <meta name="description" content="Browse page for VidyaVortex Web Service, Project WSD 2015">
    <meta charset="utf-8" />

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static "DataVortex/img/favicon.png" %}">
    <script src="{% static "DataVortex/js/jquery-1.11.1.min.js" %}"></script> 
    <script src="{% static "DataVortex/js/vidyavortex.js" %}"></script> 

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> -->

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="{% static "DataVortex/css/main.css" %}" />
	<script>
		$(document).ready(function() {
			"use strict";
			
			var active_tab = 1;
			var ordering = 'NAME';
			var deldict = [];


			/***************************************/
			/************* FUNCTIONS ***************/
			/***************************************/

			function UpdateList(order, query) {
				
				var msg = {'messageType': 'GLOBAL_GAME_LIST', 'ordering': order};

				jsonRequest(msg, 0, function(response) {
					if (query) SearchList(response, query);
					else PrintList(response);		
				});
			}

			function PrintList(list){

				var list_id = "#gamelist";
				var redirect = "/purchase/";

				$("#gamelist").html("");
				{% if user.is_authenticated %}
				$("#yourgamelist").html(""); 
				{% endif %}

				for (var i = 0; i < list.length; i++) {

					{% if user.is_authenticated %}

		      		if (list[i].isyourgame) {
		      			list_id = "#yourgamelist";
		      			redirect = "/playgame/";   
		      		}
		      		else {
		      			list_id = "#gamelist";
		      			redirect = "/purchase/";
		      		}

		      		if (list[i].candelete) {
		      			$('#yourgamelist').append('\
		      				<a id="listlink" href="' + redirect + list[i].id + '/">\
		      				<div id="gamelist_row">\
		      				<img style="width: 80px;height: 80px;display: inline" src=' + list[i].thumbnail + ' alt="thumbnail"/>\
		      				<span id="gamelist_text"> ' + list[i].name + '</span>\
		      				</div>\
		      				</a>\
		      				<div class="container-fluid" id="details">\
		      				<div class="devdetail col-md-4">Released: '+ list[i].time +' </div>\
		      				<div class="devdetail col-md-2">Rating: '+ list[i].rating +' </div>\
		      				<div class="devdetail col-md-6">\
		      				<a href="/salesinfo/'+ list[i].id +'/"><button class="delbutton" type="button">Sales Info</button></a>\
		      				<a href="/editgame/'+ list[i].id +'/"><button class="delbutton" type="button">Edit Game</button></a>\
		      				<a href="/delete/'+ list[i].id +'/"><button class="delbutton" type="button">Delete Game</button></a>\
		      				</div>\
		      				</div>');
		      				
		      		}
		      	
		      		else {
		      	    {% endif %}

		        		$(list_id).append('\
		      				<a id="listlink" href="' + redirect + list[i].id + '/">\
		      				<div id="gamelist_row">\
		      				<img style="width: 80px;height: 80px;display: inline" src=' + list[i].thumbnail + ' alt="thumbnail"/>\
		      				<span id="gamelist_text"> ' + list[i].name + '</span>\
		      				</div>\
		      				</a>\
		      				<div class="row" id="details">\
		      				<div class="detail col-md-5">Released: '+ list[i].time +' </div>\
		      				<div class="detail col-md-2">Rating: '+ list[i].rating +' </div>\
		      				</div>');
		     
		        	

		        	{% if user.is_authenticated %}

		        	}

		        	{% endif %}		
			   	}
			}

			

			function SearchList(response, query){
				var matches = [];
				var test = query.toLowerCase();
			
				for (var i = 0; i < response.length; i++) {
						if(response[i].name.toLowerCase().indexOf(test) != -1){
							matches.push(response[i]);
						}
				}
				PrintList(matches);
			}

			/**********************************************/
			/************* ON LOADUP ACTIONS **************/
			/**********************************************/

			{% if isDev %}
			$('#second_tab').click();
			{% endif %}

			UpdateList(ordering, null);

			/*********************************************/
			/************* EVENT LISTENERS ***************/
			/*********************************************/

			$('#first_tab').click(function(){
				active_tab = 1;
				UpdateList(ordering, null);
				//alert(active_tab);
			});
			$('#second_tab').click(function(){
				active_tab = 2;
				UpdateList(ordering, null);
			});

			// update list with search match set
			$('#searchStart').click(function(){
				var query = $('#searchQuery').val();
				UpdateList(ordering, query);
			});
			$('#name_ordering').click(function(){
				ordering = 'NAME';
				UpdateList(ordering, null);
			});
			$('#rating_ordering').click(function(){
				ordering = 'RATING';
				UpdateList(ordering, null);
			});
			$('#date_ordering').click(function(){
				ordering = 'RELEASE_DATE';
				UpdateList(ordering, null);
			});
			// display all games once user starts backspacing search query
			$("#searchQuery").keyup(function() {
				UpdateList(ordering, null);
			}); 

		});
	</script>

  	</head>
  	<body>	
  		<div id="container">
		  	<div id="header">
				<div id="logo">
					<a href="{% url "homepage" %}"><img src="{% static "DataVortex/img/logo.png" %}" alt="VidyaVortexLogo"/></a>
				</div>
				<div id="loginbar">
					{% if not user.is_authenticated %}
						<p><a href="{% url "login" %}">Login</a> <b>|</b> <a href="{% url "register" %}">Register</a></p>
					{% else %}
						<p><a href="{% url "logout" %}">Logout</a> <b>|</b> Welcome, {{ user.get_username }}!</p>
					{% endif %}
				</div>
			</div>
			<div id="content">
				<div id="sidebar">
					<ul>
						<li><a href="{% url "homepage" %}">HOME</a></li>
						{% if isDev %}
						<li><a href="{% url "addgame" %}">ADD NEW GAME</a></li>
						{% endif %}
						<li><a href="{% url "browse" %}">BROWSE GAMES</a></li>
						<li><a href="{% url "highscores" %}">HIGHSCORES</a></li>
						<li><a href="{% url "faqpage" %}">FAQ</a></li>
					</ul>
				</div>
				<div id="browse-box">
					<nav class="navbar navbar-default">		
						<ul class="nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#available_games" id="first_tab">Available Games</a></li>
							{% if user.is_authenticated %}
						  	<li><a data-toggle="tab" href="#your_games" id="second_tab">Your Games</a></li>
						  	{% endif %}
						  	<li class="dropdown">
						      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sort by
						        <span class="caret"></span></a>
						        <ul class="dropdown-menu">
								    <li><a href="#" id="name_ordering">Name</a></li>
								    <li><a href="#" id="rating_ordering">Rating</a></li>
								    <li><a href="#" id="date_ordering">Release Date</a></li> 
						       	</ul>
						    </li>
						    <li class="col-sm-3 col-md-4 pull-right">
					            <form class="navbar-form">
					                <div class="input-group">
					                    <input type="search" class="form-control" placeholder="Search Games" name="q" id="searchQuery">
					                    <div class="input-group-btn"> 
					                        <button class="btn btn-default" id="searchStart" type="button"><i class="glyphicon glyphicon-search"></i></button>
					                    </div> 
					                </div>
					            </form>
					        </li> 	
						</ul>
						<div class="tab-content">
							<div id="available_games" class="tab-pane fade in active">
								<div id="gamelist"></div>
							</div>
							{% if user.is_authenticated %}
							<div id="your_games" class="tab-pane fade">
								<div id="yourgamelist"></div>
							</div>
							{% endif %}
						</div>
					</nav>
				</div>
			</div>
			<div id="footer">
				<div id="footer-text">
					<p>Copyright © VidyaVortex. All rights reserved. Design by WSD-Group.</p>
				</div>
			</div>
	 	</div>
  	</body>
</html>